name: "Quality Gate"

on:
  workflow_run:
    workflows: [Quality Gate Trigger]
    types:
      - completed

env:
  GH_TOKEN: ${{ secrets.PAT }}

jobs:
  run_quality_gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref_name }}
          token: ${{ secrets.PAT }}

      - run: |
          echo 'The workflow has been triggered'
