name: "Quality Gate"

on:
  issue_comment:
    types: [created]

jobs:
  run_quality_gate:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'quality gate') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The label was added correctly'
