name: "Quality Gate"

on:
  workflow_run:
    workflows: [Quality Gate Trigger]
    types:
      - completed

jobs:
  run_quality_gate:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'The comment was added correctly and quality gate can run'
