name: 'Dispatch to trigger other repo'

on:
  repository_dispatch:
    name: Quality Gate
    types: [demo_deploy_trigger_tests]
    inputs:
      ref_name:
        description: 'Branch Reference for context'
        required: true
        default: 'incorrect-branch-name'


jobs:
  log-inputs:
    name: Log inputs
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.ref_name }}
        run: echo $MESSAGE