name: 'Dispatch to trigger other repo'

on:
  workflow_dispatch:

jobs:
  repo_event:
    name: Dispatch event with branch and repo refs
    runs-on: ubuntu-latest
    steps:
    - name: Set values
      run: |
        echo "BRANCH=feature/testing-trigger" >> $GITHUB_ENV

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PAT }}
        repository: chillianosson/action-practice
        event-type: demo_deploy_trigger_tests
        client-payload: '{"ref_name": "${{ env.BRANCH }}"}'