name: "Dispatch to trigger other repo"

on:
  repository_dispatch:
    name: Quality Gate
    types: [demo_deploy_trigger_tests]
    inputs:
      ref_name:
        description: "Branch Reference for context"
        required: true
        default: "incorrect-branch-name"

env:
  GH_TOKEN: ${{ secrets.PAT }}

jobs:
  log-inputs:
    name: Log inputs
    runs-on: ubuntu-latest
    steps:
      - env:
          BRANCH_NAME: ${{ github.event.client_payload.ref_name }}
        run: echo $BRANCH_NAME

      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref_name }}
          token: ${{ secrets.PAT }}

      - name: Comment the pull_request
        run: gh pr comment 2 --body "Hi quality gate you can now runn"
