name: 'Dispatch to trigger other repo'

on:
  repository_dispatch:
    name: Quality Gate
    types: [demo_deploy_trigger_tests]
    inputs:
      ref_name:
        description: 'Branch Reference for context'
        required: true
        default: 'incorrect-branch-name'


jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Branch supplied: ${{ github.event.inputs.ref_name }}"c