name: 'Dispatch to trigger other repo'

on:
  workflow_dispatch:

jobs:
  repo_event:
    name: Dispatch event with branch and repo refs
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PAT }}
        repository: chillianosson/action-practice
        event-type: demo_deploy_trigger_tests
        client-payload: '{"ref-name": "feature/testing-trigger", "demo-url": "fake-demo-url.com", "pr-number": "8"}'

