name: "Quality Gate"

on:
  issues:
    types:
      - labeled

jobs:
  run_if_label_matches:
    if: github.event.label.name == 'environment-available'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The label was added correctly'
